// Generated by gencpp from file livox_ros_driver/CustomMsg.msg
// DO NOT EDIT!


#ifndef LIVOX_ROS_DRIVER_MESSAGE_CUSTOMMSG_H
#define LIVOX_ROS_DRIVER_MESSAGE_CUSTOMMSG_H

#include <string>
#include <vector>
#include <array>
#include <memory>

#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/header.hpp>
#include "CustomPoint.h"

namespace livox_ros_driver2  // Change from livox_ros_driver to livox_ros_driver2
{
namespace msg
{

struct CustomMsg
{
  // Message fields
  std_msgs::msg::Header header;
  uint64_t timebase;
  uint32_t point_num;
  uint8_t lidar_id;
  std::vector<livox_ros_driver2::msg::CustomPoint> points;  // Update namespace here too

  // Constructors
  CustomMsg()
    : timebase(0)
    , point_num(0)
    , lidar_id(0)
  {
  }

  // Type aliases for ROS 2
  using SharedPtr = std::shared_ptr<CustomMsg>;
  using ConstSharedPtr = std::shared_ptr<const CustomMsg>;
  using UniquePtr = std::unique_ptr<CustomMsg>;
  using ConstUniquePtr = std::unique_ptr<const CustomMsg>;

  // Message type info
  static constexpr const char* MESSAGE_TYPE = "livox_ros_driver2/msg/CustomMsg";
};

} // namespace msg
} // namespace livox_ros_driver2

#endif // LIVOX_ROS_DRIVER_MESSAGE_CUSTOMMSG_H
